project:
  type: book
  output-dir: docs

book:
  title: "Notas de Aula: Cálculo e Geometria Analítica"
  author: "Lucas Porto"
  date: "10/6/2025"
  language: pt-BR

  chapters:
    - index.qmd
  
    - part: files/reais_intro.qmd
      chapters:
        - files/funcoes_reais.qmd
        - files/invfunc.qmd
        - files/simetria_funcoes_reais.qmd
        - files/polinomios.qmd
        
    - part: files/derivadas_prop.qmd
      chapters:
        - files/integrais_prop.qmd
        - files/ex_espiral.qmd
        - files/references.qmd
    - part: files/probabilidade_def.qmd
      chapters: 
        - files/prob_opp.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

crossref:
  thm-title: Teorema
  thm-prefix: teorema
  def-title: Definição
  def-prefix: definição
  cor-title: Corolário
  cor-prefix: corolário
  cnj-title: Axioma
  cnj-prefix: axioma
  exr-title: Exercício
  exr-prefix: exercício

    


